<img src="http://imgur.com/1ZcRyrc.png" style="float: left; margin: 20px; height: 55px">


# Telecomm EDA Challenge Lab

_Author: Alex Combs (NYC) _

---

Let's do some Exploratory Data Analysis (EDA)! As a data scientist, you often may find yourself given a data set you've never seen before, and asked to do a rapid analysis. This is today's goal.

# Prompt

You work for a telecommunications company. The company has been storing metadata about customer phone usage, as part of the regular course of business. Currently, this data is sitting in an unsecured database. The company doesn't want to pay to increase their database security, because they don't think there's really anything to be learned from the metadata.

They are under pressure from "right to privacy" organizations to beef up the database security. These organizations argue that you can learn a lot about a person from their cell phone metadata.

The telecom company wants to understand if this is true, and they want your help. They will give you one person's metadata for 2014 and want to see what you can learn from it.

Working in teams, create a report revealing everything you can about the person. Prepare a presentation, with slides, showcasing your findings.


# The Data

The [person's metadata](./datasets/metadata.csv) has the following fields:

| Field Name          | Description
| ---                 | ---
| **Cell Cgi**        | cell phone tower identifier
| **Cell Tower**      | cell phone tower location
| **Comm Identifier** |	de-identified recipient of communication
| **Comm Timedate String** | time of communication
| **Comm Type	Id**  | type of communication
| **Latitude**        | latitude of communication
| **Longitude**       | longitude of communication

# Hints

This is totally open-ended! If you're totally stumped -- and only if stumped -- should you look below for prompts. As a starting point, given that you have geo-locations, consider investigating ways to display this type of information (i.e. mapping functionality).

<font color='white'>
Well for starters, he's in Australia!

Ideas for things to look into:
- where does he work?
- where does he live?
- who does he contact most often?
- what hours does he work?
- did he move?
- did he go on holiday?  If so, where did he go?
- did he get a new phone?

Challenges:
- how does he get to work?
- where does his family live?
- if he went on holiday, can you find which flights he took?
- can you guess who some of his contacts are, based on the frequency, location, time and mode (phone/text) of communications?


If you're stuck on how to map the data, you can try "basemap" or "gmplot", or anything else you find online.
</font>

In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
import scipy.stats as stats

plt.style.use('fivethirtyeight')

%matplotlib inline
%config InlineBackend.figure_format = 'retina'

In [2]:
df = pd.read_csv(r'C:\Users\Daniel_Heffley\Desktop\jan 5 2020\DAT-course-materials-students-master\homework\metadata.csv', encoding='latin-1')

In [3]:
df.head()

,Cell Cgi,Cell Tower Location,Comm Identifier,Comm Timedate String,Comm Type,Latitude,Longitude
0,50501015388B9,REDFERN TE,f1a6836c0b7a3415a19a90fdd6f0ae18484d6d1e,4/1/14 9:40,Phone,-33.892933,151.202296
1,50501015388B9,REDFERN TE,62157ccf2910019ffd915b11fa037243b75c1624,4/1/14 9:42,Phone,-33.892933,151.202296
2,505010153111F,HAYMARKET #,c8f92bd0f4e6fb45ed7fce96fc831b283db2b642,4/1/14 13:13,Phone,-33.880329,151.205690
3,505010153111F,HAYMARKET #,f1a6836c0b7a3415a19a90fdd6f0ae18484d6d1e,4/1/14 13:13,Phone,-33.880329,151.205690
4,5.05E+106,HAYMARKET #,f1a6836c0b7a3415a19a90fdd6f0ae18484d6d1e,4/1/14 17:27,Phone,-33.880329,151.205690

In [9]:
pd.options.display.max_rows = 130

In [10]:
df['Cell Tower Location'].value_counts()

BALGOWLAH HAYES ST                          4301
CHIPPENDALE                                 1084
SUNDERLAND ST                                723
REDFERN TE                                   712
HAYMARKET #                                  563
BRICKWORKS                                   501
HARBORD 22 WAINE ST                          465
FAIRLIGHT 137 SYDNEY RD                      454
MANLY #                                      231
NEW TOWN                                     197
CHINATOWN                                    161
BEECHWORTH                                   112
BALGOWLAH VILLAGE SHOPPING CENTRE IBC        106
MANLY SOUTH STEYNE                            92
BROADWAY OTC                                  85
MASCOT INTERNATIONAL AIRPORT TERMINAL T1      65
71 MACQUARIE ST                               49
SURRY HILLS 418A ELIZABETH ST                 45
MANLY NTH STEYNE                              40
MASCOT M5 MOTORWAY EMERGENCY STAIRS           33
BALGOWLAH TE                                  30
NEUTRAL BAY MILITARYRD                        29
BENALLA EAST                                  29
SURRY HILLS                                   22
SYDNEY 505 GEORGE ST                          22
SYDNEY DOMESTIC TERMINAL T2 - VIRGIN          22
SPIT BRIDGE                                   20
THOONA                                        20
SEAFORTH                                      19
HOBART AIRPORT                                17
DEE WHY                                       16
ULTIMO BULWARA RD                             16
COLLINS ST (HOBART)                           15
KENT #                                        15
HAYMARKET TE LEVEL 5 SRA BTS HOTEL            14
CREMORNE #                                    14
MASCOT AIRPORT FAC3                           13
ULTIMO; 616-620 HARRIS ST                     10
CENTRAL SRA DONOR                             10
THE ROCKS 55 HARRINGTON ST                     8
NORTH HOBART 1800                              7
LENEVA; WODONGA TIP OFF BEACHWORTH RD          7
CREMORNE JUNCTION; GERARD ST                   6
DARLINGHURST                                   6
NORTH SYDNEY 54 MCLAREN                        6
SYDNEY 131 YORK ST                             5
AIRPORT LINK                                   5
ZETLAND 757 ELIZABETH ST                       5
SYDNEY 450 GEORGE ST                           4
COWAN 1051 PACIFIC HWY                         4
LUTANA                                         4
BEROWRA WINDY BANKS INTERCHANGE                4
POLICE HEADQUARTERS                            4
MAQUARIE ST                                    4
MOUNT RUMNEY                                   3
SYDNEY 2 CASTLEREAGH STREET                    3
SYDNEY INTERNATIONAL AIRPORT RAILWAY STN       2
COWAN LOT 1                                    2
WAHROONGA #                                    2
ROSEBERY DUNNING AVE                           2
MASCOT 201 COWARD ST                           1
REDFERN; 495 CLEVELAND ST                      1
MELB AIRPORT TERM                              1
DALLEY2 #                                      1
NEWTOWN TE                                     1
GRAND CHANCELLOR 1800                          1
EDGECLIFF EXCHANGE (PO)                        1
CARLTON COLLEGE SQ                             1
BROOKLYN PACIFIC HWY                           1
DAVID JONES                                    1
ASCOT VALE SOUTH                               1
Name: Cell Tower Location, dtype: int64

In [11]:
df['Comm Identifier'].value_counts()# I would guess the top communicator would be a spouse and the next three top
# communicators are his children? Total conjecture, but a worthwhile guess. I would also say the other top communicators are
# various other family member and friends. The communicators with one communication are probably spam calls/ texts.
# We can estimate from this how many spam calls the customer gets

bc0b01860486b0f0a240ce8419d3d7553fe404ab    219
12e3d1b0c95aa32b6890c4455918dfc10e09fb51    146
91aba4a11359ff3af7902428d20cfa7e676c36e7    144
a24a4646d074a779b45b34b943a47bf33168f791    133
6bbc17070aa91e2dab7909b96c6eecbd6109ba56     83
a804558e420ececf05faedf05722704a115f1b50     62
cd3b39466869088df4904451c626591cc500e4ba     56
c22670da93038f568c4a3bd8ae22f9e6fef2c5a2     44
70e1f163d854d4e9b63e9a3f4056ced467567d85     39
c521537546eee0e62e2d8e98e831ac11edbf10cc     31
746da741fb2ac66a5130b1ce2ee4615a58b356ae     29
62157ccf2910019ffd915b11fa037243b75c1624     28
a5834ee77b2c1dd26c78966f5e2c989c453878ba     26
c13b4711ebc07ab70537d8d6f6326edb1c7b419a     17
6dad3704c00eb122d2f183ca612ef8990cc72bea     17
0767e517fa09e8bcc0b87461133830378a107619     16
b10d076fa3354b695ffa1e5f0ec5178d792fea95     16
b9ac4ec5dea89a5d8cac2854bfa0161989d3aa66     15
c8f92bd0f4e6fb45ed7fce96fc831b283db2b642     14
ce4393a832fb45f7dddcb5c2147fd086763acfb4     13
dc6774d10eeca42629f043d3649f1edf903b0dab     11
7aef968bde08f5a426621d2b4c766e2e36c593e6     11
a3dfe2f2e41135cee91149d5d5ffb323b30a6354      8
7f777edca3555fc1859fa24bddab1ed9dc5936d7      8
6616bfb47a35997d9d91c2d8d5fa4970ecbf501d      7
69e1dedd013f46b763f0a8682fcebb665aa4d099      6
e09b94f3bc39fe9e125904ce03f037899fd54c60      6
852715872cb9adf5424a385d189b83b5f88ecd73      6
e16da158e1f7a08bc49e766b70fa7c8eb0c320a2      5
715da36ed3a6e2df73ef1a86f571c3b1de229d1a      5
6379a5790879c6b6bc212c0fcc52c578a02f36ce      5
73269cfd2741bca3d06ed0d3e0e5f325cf4efddb      4
9096f2e42f69957aebc0e013a92680b2b9bd06c3      4
8e009917afae92a1d48d73229678ca56ba16f3b6      4
2b0dd6e3c91c857142e3a85afb476b8b7a5a22fb      4
f1a6836c0b7a3415a19a90fdd6f0ae18484d6d1e      3
4f36cb17f79b4cbf8d10a21f2af868cd5f41936e      3
67c07d37c0f4d15d13c03c83030ca29450920a10      3
585c55ca51a12d0f87a1f7faa38a6cdd5b8e67c3      3
cad22015a5d60bd80c4a24a313f9962f6890a8b8      3
af87051f8c64d7e75f7044ea21acd592fee37d6e      3
e925cff3596db298e7f5d7cd31306e790b7fe7be      3
de40c5c1f9249f95f7fb216931db58747afef74f      3
76410549febefdf637cd95e6608081a1e44f3bf7      3
3b8f9de35d3fb92afd7243449b7ddf5ca22eb29c      2
c748478c467be6a3adb9729eccb88e49d8270785      2
c20d10fed2182b6bdbe1c1d8583054cf86bac113      2
7b79c2b0f76f45c73ae121ece7cc9561dc3934b5      2
632596051800e3f75b19e43a02feb73906cb0585      2
53888f253a53f8f4c99b01ae9f36cce30fd3c3f8      2
ab68edd9bb5cf9fbb639e5ff83dc45b20d783250      2
3eca740265c282cf6daa0de5ebb20d53f586431d      2
c39978873f97c3f342a9bfb1402e941d2ea635a6      2
ec06f67bc5a1a38bd1a677f67ae0284f2bd89a1b      2
b21cdacfa703e85a8e5557171f92b4a3d7888d3a      2
940f140cc66e34363d81ec5d0c8d9c05c72d6887      2
a0b2423b43e7bbe69fd72c439b3872501300a960      2
dba0dabbd6fc1c2ec9c45bde115473124ed318f2      2
2647503c0eeea783f96063c7789cc49b8db02ce4      2
8d75adc43c36067fe7d0b2c0a0c1296aad394547      2
1f07e1e8ac6e594c7fd72f116f662592294e5d79      2
313466f2e1277eee64d7c7314b19537d7543cce9      2
133bcd96ba88135b020191d490b0ab1cdd068190      2
1c8f2e2c973b2fb1dc9bcc5af199a94607bbb8de      1
55a57ead5e9d2af758c5544b628e1b1e502f37c8      1
3b7e0a17dd8bf9b01adda39608795a00fb85795f      1
92db0fe35888ceccd6853eb396b5f4722bfed3b3      1
ee32087ac758e7b5cccc5f29c5019dc4f6675418      1
454a93121d323bd849d24a34b822459b94f55cf8      1
457389578b94478f576af008c58508d7c53cdfeb      1
0e257b2a4a3ba2a6e3494110353c94f20ab2c608      1
7cb96eadd3ff95e25406d24794027c443c0661c5      1
2c14eb651876b4329ce7a69193d80ee729ab416d      1
7325eeeaf3601e7d67d601e7fbfd5282764c5c3a      1
7442b8b2c68f4ffea121be1750e81bc5334e3d24      1
b5238f237b241802d59fce177e4f9f016ae3d4f6      1
4c799141b694e03fd5bd7507e048aa028026793c      1
81d04c5a17bdba7d504f90cf837a74f640a387cd      1
4e0e6ccf6a291980aeb0cda492ec4e62697d231c      1
55c9fbf7495f31d631bf0f26a00e4494f1c5715e      1
6ce4ad58c49c34d1bf2eb8f0daa92a0669d43841      1
809b9fef422c854085624d5de2ac512944ca4902      1
bacba6fa36551491ea37e609594af1caa7771f56      1
66f32c1163d0e597983b65c51f5a477070ad3785      1
46978471e73705549c6a0d4c21dcfb9b5c75a261      1
d40020272cf978c0c55e05711679c6226d78109e      1
5821bc2ed11a22740546ad49640518d018c13fba      1
0c08dc84a5832bec24754f4bb455d969aeb8d3eb      1
ee256d4b16ede847d9d803a23b8b21cf19c19cef      1
9039f13710c84d207864169cacc97ddc1b5accb1      1
c6a13ece9733678b4108757dfe586e4180cae7bd      1
018cad8a2f878aedb076fed31a884ce4660ba3f8      1
1334c7802f812ef1165801e481205d288c2bfbf3      1
04c59eb3b86144d1ac376a34bb3a7849ca5d5957      1
630c8438e4e5b0ca3b649a321787003bbf53f631      1
d31c02409bcdb4ba9d6596e000e0bc50b041b947      1
fdd607340fe1953e0309b180ce432fbcd0c55d46      1
8cf35d5b8a3c98ccfa54ed8df253822cb7b39c90      1
34d891bf905e5683a643d3f58661090d687b869c      1
cfd4c96c17607be179c0f62d06ddd5f91d3be304      1
420e9d55ed695a32306c7c1b6b7e97d939fa5c26      1
78bda7c1148bf47171a300ece6339c3f92e17a8a      1
8a84ca2b5f3bd85c6e8d6381eee3036a8e5a334c      1
832d39b1f31ad2ddd1720abdd4dacd365079e2db      1
9273651b8b7673b1cb73fbfd69a810ea30e07666      1
cc084c3f3bc40b2dae94bc0a9f2487fe1cc823d0      1
3bb33b7b6d81c164b1d3d4f931e4c90c5e83537b      1
df169b4ccc050b2b5fc842b941c9b65ac790d319      1
3b76363042042fe1111495e11de64095821db877      1
ece3986f83274bf17c3ddbe12cd8ec31e855ea44      1
e1c8d908b3c12914e6a5108e3f365888357e6b19      1
3261efc7a67a95c5f9da2d1cbee7bbb236a1227e      1
c7436c3d0d6a406563a5260e242affab79a368ba      1
3df9fcfca4fec82406bde03ea50379f8f66ed519      1
e16514aa8bdc83ba0976bca8a1dc20c9b391dbe6      1
f5411dda04b275b907e9de3518ff84f7117de909      1
b421e001abcb383e71191aee0903abe4832313a3      1
a7bacedaea853cb0ca57d3a32c17bff1b52f778b      1
10b12424a13d79ad82647d552ecc456d3caa4093      1
947258734417008cf6ba7e4409f0eed94af77b95      1
3274802c767c077c0ce3f6c2f76fabe35129f696      1
6d40e297ca2af7310eeb00517df94a9dbfdfcb2c      1
506f74c16a228ac966a2c785cc5cdb32946c769d      1
caca077c49aa8bc43ed6a93fb15e37027d116161      1
dabf001d9a1ddf353d4b0679e0bbf68f1fea3c8b      1
42c7626a5bef865936dbb7d42a4019bd8f26bbc8      1
7e3faa2087b9a8d1a14287302a2142bf93dde27e      1
113a18cdffeb3c883204cb5a1f4e67e2ab8c9b77      1
0309cb582e2b4fb9f8965addbbb147fcc476f941      1
4b12e682d816d603ca3820581e31fe1ce71d3e7f      1
Name: Comm Identifier, dtype: int64

In [16]:
df['lat long'] = df['Latitude'].astype(str) + ' ' + df['Longitude'].astype(str)

In [17]:
df.head()

,Cell Cgi,Cell Tower Location,Comm Identifier,Comm Timedate String,Comm Type,Latitude,Longitude,lat long
0,50501015388B9,REDFERN TE,f1a6836c0b7a3415a19a90fdd6f0ae18484d6d1e,4/1/14 9:40,Phone,-33.892933,151.202296,-33.89293336 151.20229619999998
1,50501015388B9,REDFERN TE,62157ccf2910019ffd915b11fa037243b75c1624,4/1/14 9:42,Phone,-33.892933,151.202296,-33.89293336 151.20229619999998
2,505010153111F,HAYMARKET #,c8f92bd0f4e6fb45ed7fce96fc831b283db2b642,4/1/14 13:13,Phone,-33.880329,151.205690,-33.88032891 151.2056904
3,505010153111F,HAYMARKET #,f1a6836c0b7a3415a19a90fdd6f0ae18484d6d1e,4/1/14 13:13,Phone,-33.880329,151.205690,-33.88032891 151.2056904
4,5.05E+106,HAYMARKET #,f1a6836c0b7a3415a19a90fdd6f0ae18484d6d1e,4/1/14 17:27,Phone,-33.880329,151.205690,-33.88032891 151.2056904

In [18]:
df['lat long'].value_counts()# Here we can see where the customer is when his phone is used. The top two results
# are in Sydney, Australia. The customer probably lives at the number one location and works at number two location. 
# The number three location is in Tasmania, Australia. Possibly a vacation home? It seems the customer spends most of his
#time in Sydney and goes on trips to Tasmania

-33.78815 151.26654                       4301
-33.88417103 151.20235                    1084
-42.843379999999996 147.29568999999998     723
-33.89293336 151.20229619999998            712
-33.88032891 151.2056904                   563
-42.859840000000005 147.29215              501
-33.779333 151.276901                      465
-33.79661 151.27756000000002               454
-33.796679 151.285293                      231
-42.85307 147.31531999999999               197
-33.87829 151.20345                        161
-36.3567 146.7136                          112
-33.793648 151.263934                      106
-33.799479999999996 151.28933999999998      92
-33.884603000000006 151.195643              85
-33.937558 151.1657                         65
-33.861129999999996 151.21293               49
-33.8864 151.2088                           45
-33.791965000000005 151.286589              40
-33.946740000000005 151.16714               33
-33.79345 151.2631                          30
-36.502179999999996 146.11177               29
-33.8294 151.21828                          29
-33.88024 151.20569                         24
-33.88964 151.21142                         22
-33.93416 151.17938                         22
-33.87513 151.20584                         22
-33.80638 151.24698                         20
-36.331075 146.075432                       20
-33.79275 151.24125                         19
-42.83762 147.50575                         17
-33.879 151.19801                           16
-33.75949 151.28135                         16
-42.88194 147.32893                         15
-33.86633 151.20469                         15
-33.83096 151.22548999999998                14
-33.93285 151.1842                          13
-33.88058 151.20046000000002                10
-33.85947 151.20748999999998                 8
-42.87457 147.31788                          7
-36.16793 146.88306                          7
-33.87814 151.2136                           6
-33.828072999999996 151.226275               6
-33.83415 151.20889                          6
-33.90533 151.205781                         5
-33.87215 151.20614                          5
-33.923217 151.187345                        5
-33.6038 151.1639                            4
-42.88029 147.32808                          4
-42.82842 147.30784                          4
-33.87055 151.20793                          4
-33.63599 151.1469                           4
-42.884809999999995 147.32748                4
-42.8606 147.4542                            3
-33.86655 151.21033                          3
-33.934674 151.16451999999998                2
-33.71763 151.11658                          2
-33.57839 151.18445                          2
-33.91132 151.20395                          2
-33.55731 151.19353                          1
-33.86285 151.20843                          1
-33.87932 151.23802                          1
-37.7778 144.93                              1
-33.89233 151.21653                          1
-37.670418 144.848243                        1
-33.8703 151.2101                            1
-33.89605 151.17963999999998                 1
-42.881009999999996 147.33346                1
-37.7929 144.96873                           1
-33.924799 151.188043                        1
Name: lat long, dtype: int64

In [ ]:
#Assuming the customer has his phone on him at all times, he has only been at the coordinates above in the year
# shown in the metadata

In [22]:
df['Comm Type'].value_counts() #The customer calls more than texts. Signals older customer?

Internet    9102
Phone        717
SMS          657
Name: Comm Type, dtype: int64

In [24]:
top_comm_df = df[df['Comm Identifier'] == 'bc0b01860486b0f0a240ce8419d3d7553fe404ab']

In [25]:
top_comm_df['Comm Type'].value_counts()#Customer mainly texts top communicator

SMS      210
Phone      9
Name: Comm Type, dtype: int64